# Generated by Django 6.0.4 on 2026-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_charger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
